/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Bittorrent-Chain Docs",
  "tagline": "Dinosaurs are cool",
  "url": "https://your-docusaurus-test-site.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/bittorrent-logo.png",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "zh-Hans",
      "zh-hant"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/tron/Desktop/newbttcdoc/bttc-docs/sidebars.js",
          "editUrl": "https://github.com/bttcprotocol/bttc-docs/tree/master",
          "path": "docs",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": "/Users/tron/Desktop/newbttcdoc/bttc-docs/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "hideOnScroll": true,
      "title": "Bittorrent-Chain Docs",
      "logo": {
        "alt": "Logo",
        "src": "img/bittorrent-logo.png",
        "target": "_self"
      },
      "items": [
        {
          "label": "Apps",
          "position": "right",
          "items": [
            {
              "href": "https://bt.io/wallet/?language=EN",
              "label": "Wallet",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://bt.io/bridge?language=EN",
              "label": "Bridge",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://bt.io/staking?language=EN",
              "label": "Staking",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://bt.io/bttcswap?language=EN",
              "label": "Swap",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://bttcscan.com/",
              "label": "Explorer",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://scan.bt.io",
              "label": "BTTCSCAN",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://bt.io/swap/?language=EN",
              "label": "BTT Redenomination",
              "target": "_blank",
              "rel": null
            }
          ]
        },
        {
          "label": "Community",
          "position": "right",
          "items": [
            {
              "href": "https://discord.com/invite/qrxfbgQYGa",
              "label": "Discord",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://twitter.com/BitTorrent",
              "label": "Twitter",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://t.me/BitTorrentChain",
              "label": "Telegram",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://medium.com/@BitTorrent",
              "label": "Medium",
              "target": "_blank",
              "rel": null
            }
          ]
        },
        {
          "label": "Security Audit",
          "position": "right",
          "items": [
            {
              "href": "https://bttc.bittorrent.com/doc/SlowMist%20Audit%20Report%20-%20BitTorrent%20-%20TRON.pdf",
              "label": "Bittorrent TRON",
              "target": "_blank",
              "rel": null
            },
            {
              "href": "https://bttc.bittorrent.com/doc/SlowMist%20Audit%20Report%20-%20BitTorrent%20-%20Ethereum.pdf",
              "label": "Bittorrent Ethereum",
              "target": "_blank",
              "rel": null
            }
          ]
        },
        {
          "to": "docs/contribute/guidelines",
          "label": "Contribute to the Docs",
          "position": "right"
        },
        {
          "href": "https://github.com/bttcprotocol",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ]
    },
    "algolia": {
      "indexName": "matic_developer",
      "appId": "16JCDEHCCN",
      "apiKey": "757c19b23127e9c6959da7f13b71cfab",
      "contextualSearch": false,
      "algoliaOptions": {},
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Apps",
          "items": [
            {
              "label": "Wallet",
              "to": "https://bt.io/wallet/?language=EN"
            },
            {
              "label": "Bridge",
              "to": "https://bt.io/bridge?language=EN"
            },
            {
              "label": "Staking",
              "to": "https://bt.io/staking?language=EN"
            },
            {
              "label": "Swap",
              "to": "https://bt.io/bttcswap?language=EN"
            },
            {
              "label": "Explorer",
              "to": "https://bttcscan.com/"
            },
            {
              "label": "BTTCSCAN",
              "to": "https://scan.bt.io"
            },
            {
              "label": "BTT Redenomination",
              "to": "https://bt.io/swap/?language=EN"
            }
          ]
        },
        {
          "title": "DevCenter",
          "items": [
            {
              "label": "Github",
              "href": "https://github.com/bttcprotocol"
            },
            {
              "label": "Faucet",
              "href": "https://testfaucet.bt.io/"
            },
            {
              "label": "Testnet",
              "href": "https://test.bt.io"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.com/invite/qrxfbgQYGa"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/BitTorrent"
            },
            {
              "label": "Telegram",
              "href": "https://t.me/BitTorrentChain"
            },
            {
              "label": "Meidum",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 Bittorrent-Chain | All rights reserved"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
